### ISSUE TITLE
[BUG] Header and Footer weird behaviour with typst 0.11.0

### ISSUE THREAD

**Issue by JustRayCB** [Pablo-Gonzalez-Calderon/chic-header-package#12]
**Describe the bug**
If there is nothing that follows a heading (whatever his level) the elements inside the header or footer become bigger and bolder

**To Reproduce**
Using the Readme's example:
```typst
#import "@preview/chic-hdr:0.4.0": *

#set page(paper: "a7")

#show: chic.with(
  chic-footer(
    left-side: strong(
        link("mailto:admin@chic.hdr", "admin@chic.hdr")
    ),
    right-side: chic-page-number()
  ),
  chic-header(
    left-side: emph(chic-heading-name(fill: true)),
    right-side: smallcaps("Example")
  ),
  chic-separator(1pt),
  // chic-offset(7pt),
  chic-height(1.5cm)
)

= Introduction
#lorem(30) // uncomment this line to see the change

#pagebreak()

== Details
#lorem(70) // or this one
```

**Screenshots**
Default, when there is something that follows a heading
![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/92854970/f00da5c5-d4b4-409f-8d45-de9014fb519b)

With the second lorem statement is commented:
![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/92854970/0833d326-4961-4788-af58-4c4aace87c83)

**Additional context**
X

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi! It seems that this bug is related to Typst itself and not the package. For instance, writing this code

```typst
#set page(paper: "a7", header: [
  Example title
])

= Introduction
```
Produces this:
![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/30756770/ebcd7a44-bab3-4d04-94b2-9fac5b41bb87)

Which is the same bug. A temporary solution to this problem would be writing some text below the headings, so the bug disappears:
![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/30756770/b6de78f9-75ec-4baa-b568-dcd918d9b83a)
