### ISSUE TITLE
Header possibly incorrect in edge case

### ISSUE THREAD

**Issue by davidleejy** [Pablo-Gonzalez-Calderon/chic-header-package#5]
Hi Pablo,

Thanks for creating the chic-header package. I had great fun using it and am glad it exists.

I was playing around with headers and came across what I think might be a minor bug. I think it's easiest to convey what I'm seeing by sharing a screenshot & the simple code for reproducing it:

![Screenshot 2023-10-02 at 2 39 39 PM](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/1690072/4a4d7e5b-74af-428f-9bcb-6a38a8656d32)

I think the header on the 2nd page (circled in the figure) should be **B**. Do you feel the same way?

Code to reproduce:

```typst
#import "@preview/chic-hdr:0.3.0": *

#set page(paper: "a7")

#show: chic.with(
  chic-header(
    left-side: emph(chic-heading-name())
  ),
  chic-separator(1pt)
)

= A
#lorem(10)

== AA
#lorem(10)

=== AAA
#lorem(30)

= B
#lorem(30)

== BB
#lorem(70)
```

Thanks and hope you have a great week ahead 🌅

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi! 😁

I think this is the correct behaviour 🤔, `chic-heading-name()` returns the previous heading name, but, if there's no headings before, returns the next one. I made this a while ago, trying to find a "good" way to show heading's names.

But, honestly, I think it's not the best implementation. While reading this Issue I've got an idea to solve this: adding two parameters.

- One parameter could be ``direction`` which indicates if the heading search process should get the ``next`` or the ``previous`` heading.
- The second parameter would be ``fill``, which indicates that "if no heading were found in the given ``direction``", use the opposite direction for seeking another heading name to fetch.

What do you think? Will this be more customizable? I would like to minimize the confusion the current implementation makes 🧐

**Comment by davidleejy** [comment]
Hi Pablo! 🙂

> I think this is the correct behaviour 🤔

Just to quickly bounce this past you, do we feel that the following is correct behavior?

<img width="246" alt="Screenshot 2023-10-03 at 3 12 17 PM" src="https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/1690072/da0e088f-2a1e-4322-bd49-31e60322cd18">

I kind of feel the header circled should be "Operations" instead 😆

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hmmm. Yeah, it feels a bit wrong 😅

I think I'm going to change the default behaviour and make a "more sofisticated" ``chic-heading-name()`` function for being more customizable and "more natural" to see.

Thank you for pointing this 😁

I'll comment here when the changes are done and uploaded to Typst packages' repo, so I mark this as closed 😉

**Comment by Pablo-Gonzalez-Calderon** [comment]
Oh, that's interesting 🤔

Surely another option in ``chic-heding-name()`` could be "``level``" for indicating "until which heading level fetch headings".

Thank you for showing this. I should also look other "real life" examples for improving the package 🤔

I'm excited to make these new changes 😁, but first I need to finish some work with [showybox-package](https://github.com/Pablo-Gonzalez-Calderon/showybox-package) and some academic tasks before putting my soul into it.

In the meantime, if you observe another feature that would be relevant, tell me, so we can discuss about it 😁

**Comment by davidleejy** [comment]
Hi Pablo! 🙂 No worries, I think it's cool that you've developed this useful open source project and it shouldn't detract from your other commitments and other things that you find fun in pursuing.

Who knows, if we wait for a bit, someone might chance upon this issue ticket and submit a pull request 😎. I would poke around the code out of curiosity but I also have academic matters to attend to haha.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi David! 😁

I had some free time and tried to implement the changes discussed here.

Now the changes are available in this repository, in the (still in development) version 0.4.0 of chic-hdr. Below is a summary of the changes done to ``chic-heading-name()``

## Summary

`chic-heading-name()` now returns the next heading name in the `dir` direction. The heading must have a lower or equal level than `level`. If there're no more headings in that direction, and `fill` is ``true``, then headings are sought in the other direction. Parameter details are:

- `dir`: Direction for searching the next heading: ``"next"`` (from the current page, get the next heading) or ``"prev"`` (from the current page, get the previous heading). Default is `"next"`.
- `fill`: If there's no more headings in the `dir` direction, indicates whether to try to get a heading in the opposite direction (default is ``false``).
- `level`: Up to what level of headings should this function search (default is ``2``).

***

I would appreciate if you can try a little bit these new changes and tell me if they work well for you 😉 Also, any comments are welcome in order to polish these new features 😁

**Comment by davidleejy** [comment]
Hi Pablo! That was fast 🏃🏻💨. Would it make sense to push it to Tyspt's package manager like was done for v0.3.0? At the moment, I am facing difficulty importing the 0.4.0 version from "preview" in Typst's web application. Am excited to try your new feature out! 🎆🎇 With additional flexibility in how headers are chosen and printed, I think more Typst users will be drawn to using chic-hdr. 😎

**Comment by Pablo-Gonzalez-Calderon** [comment]
> Would it make sense to push it to Tyspt's package manager like was done for v0.3.0? 

Hi David! 

As far as I know, modifying a previous version wouldn't be allowed in Typst packages repository.

> At the moment, I am facing difficulty importing the 0.4.0 version from "preview" in Typst's web application. Am excited to try your new feature out! 🎆🎇

Yeah, that's because it isn't yet uploaded to the Typst packages repository 😅. As far as I know you can download the source code and "upload it" to the ``@local`` folder in your local Typst CLI version (and works similar as the ``@preview`` folder). If I found more complete instructions on this, I'll add them in a new comment

> With additional flexibility in how headers are chosen and printed, I think more Typst users will be drawn to using chic-hdr. 😎

I hope so. In the Typst's discord some users have been also noticing the package and tried it 🤞

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi again!

Here's a link of what I found about local packages:

https://github.com/typst/packages#local-packages

**Comment by tingerrr** [comment]
I have a working solution which will skip showing a heading when there is a heading on the current page. It does this with some location specific checks that rely on knowing the page margin.

Once get rules OR a more sophisticated ancestry querying API is implemented, it could function on its own without having to know the top margin of the document.

If you're interested in that approach I'll PR it.

**Comment by tingerrr** [comment]
My implementation will not really work with the `dir` and `fill` parameters as it assumes that you are a) in the header looking for the currently "active" section, so to speak. I also have a workaround to make this work in the footer. Are these parameters actually used in practice?

My implementation is also general enough to support arbitrary filtering of the last and next heading, it seems here only filtering by a range of levels is supported. But I think it may be too general and complicate the otherwise simple API of chic.

I could also release it as a standalone package as I initially intended if API complexity is a concern, I rely more on lambdas with location arguments and such.

It looks similar to this:
```typst
#set page(header: current-section(
  sel: (heading, h => h.level <= 2), // filter optional
  prev-filter: h => h.numbering != none
))
```

If I release it as a standalone package, you could pull it in and provide a subset of the implementation, but it would no longer support the different direction and filling.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi! Sorry for the late reply, I was kind of busy with some academic stuff 😓

> My implementation will not really work with the `dir` and `fill` parameters, as it assumes that you are in the header looking for the currently "active" section, so to speak. I also have a workaround to make this work in the footer. Are these parameters actually used in practice?

Hmmm. Since the main problem of this Issue was solved by having a "more custom" way for getting headers, I think removing those options would be a step backwards. Also, I consider that ``dir`` and ``fill`` are practical for people who won't like the default behaviour of ``chic-heading-name()`` function. So, in order to offer an option for everyone, keeping them would be nice (although it isn't something "written in stone").

> My implementation is also general enough to support arbitrary filtering of the last and next heading, it seems here only filtering by a range of levels is supported. But I think it may be too general and complicate the otherwise simple API of chic.

Maybe complicate makes the package more customizable? It's a good question. When I think of allowing level-filtering I think on my daily works with Typst. I usually only have "important titles" in level 2 at most, and even I remove the heading numbering in titles with greater level as they are less significative. But this could just me 🤔

> I could also release it as a standalone package as I initially intended if API complexity is a concern, I rely more on lambdas with location arguments and such.

I think it'll be also a good base for a package, but an integration with chic would be nice 🤔

> It looks similar to this, but works without any parameters if used in the header on a4-paper:
> 
> ```typst
> #set page(header: current-section(
>   sel: (heading, h => h.level <= 2),
>   prev-filter: h => h.numbering != none
>   next-filter: default.next-filter.with(top-margin: ...)
> ))
> ```

Hmmmm. I kind of get an idea of what it does, but I would prefer to see the code in a PR to check the changes in the main code, because, as I see it now, it requires to modify the ``page`` setter, something that the current ``chic-heading-name()`` function does not do, so I don't know the actual behaviour of that in real world cases.

Who knows, maybe your changes make the package's code simpler 😉

**Comment by tingerrr** [comment]
You can see the implementation [here](https://github.com/tingerrr/hydra), I was about to release this as a package when I read about `chic-header`.

**Comment by Pablo-Gonzalez-Calderon** [comment]
> You can see the implementation [here](https://github.com/tingerrr/hydra), I was about to release this as a package when I read about `chic-header`.

Hi! I've checked the code and it's really good. But it seems to me that trying to implement it inside chic-hdr would be kind of complicated, as it seems that it'll override some chic-functions behaviours.

Anyways, it looks more concise than chic-header for setting the heading names in the header, and it would be very useful for people who is experienced in Typst, so it would be great to have it as an independent package. Definitely, I would use it 😁

Thank you anyways for waiting my responses and being interested in contributing to the package 😉

**Comment by tingerrr** [comment]
I'll release it as a package then, I'll likely add some other primitives like easy chapter styling to them later on, so it's not just that a single header function.

**Comment by tingerrr** [comment]
You can now use `hydra` to work around this limitation for now:

```typst
#import "@preview/chic-hdr:0.3.0": *
#import "@preview/hydra:0.1.0": hydra, default as hydra-default

#set page(paper: "a7")

// this is a hack because of an oversight by me when making `hydra`
#set heading(numbering: (..args) => [])

#show: chic.with(
  chic-header(
    left-side: hydra(next-filter: hydra-default.next-filter.with(
      // this is the default margin for a7 `(2.5 / 21) * smaller-page-size`
      top-margin: (2.5 / 21) * 74mm
    )),
  ),
  chic-separator(1pt)
)

= A
#lorem(10)

== AA
#lorem(10)

=== AAA
#lorem(30)

= B
#lorem(30)

== BB
#lorem(70)
```

Unfortunately, I forgot to remove the numbering check in `next-filter`, which requires this little hack if you don't use numbered headings. Otherwise, it should work fine.
![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/137803093/a1e14f59-84ba-4584-9940-1cc6cb59aaae)


I'll fix that in the next release and add some configured page margins.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi @davidleejy and @tingerrr !!!

I'm glad to announce that the manual is finished and loaded in the repo (I've included a link to hydra package in the `chic-heading-name()` section, so people can try it for fetching heading names instead of using the default function😉).

I will make a PR in the Typst package's repo soon, so the changes will be available for everyone.

Thank you both for your ideas, time and patience 😊
